services:
  jenkins:
    build:
      context: .                  
    image: jenkins-with-docker:lts
    environment:
      DOCKER_GID: "${DOCKER_GID}"     
      #JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: